### ISSUE TITLE
Logging report not sending to email

### ISSUE THREAD

**Issue by berzinsk** [techatspree/androlog#10]
Here is the code from .properties file:

`````` androlog.report.active=true
androlog.report.reporters=de.akquinet.android.androlog.reporter.MailReporter
androlog.reporter.mail.address=MY_EMAIL_ADDRESS
androlog.report.default.level=VERBOSE
androlog.report.log.items=10
androlog.report.trigger.level=INFO```

Then in MainActivity.java I initialize the androlog: ```Log.init(this);```
And then log some messages ```Log.i("message", "message");```

But nothing is sent to my email. What am I doing wrong?
``````

**Comment by ebiermann** [comment]
Hello berzinsk,

Does the MailReporterTest work successfully for your device? Androlog uses the intent android.intent.action.SEND to send the email. Even if no means of sending are configured on the device yet, you should at least get the option to setup a mail account.

Regards,
Enrico

**Comment by berzinsk** [comment]
Yes it worked succesfully. Was my fault!
