### ISSUE TITLE
Log.reset does not reset the default unhandled exception handler

### ISSUE THREAD

**Issue by threegerbils** [techatspree/androlog#11]
If init is called more than once (in my case from a foreground service and an activity binding to the service, either of which might occur first) the default exception handler will be called twice as the second init will pick up the handler set in the first init as the original handler.
The result in my case is that two reports will be generated for each unhandled exception

**Comment by ebiermann** [comment]
Thanks for catching this bug. It is fixed it on master and we will release a new version soon.

Enrico
