### ISSUE TITLE
Allow wildcards or package filtering with property file configuration

### ISSUE THREAD

**Issue by kovmarci86** [techatspree/androlog#4]
There is no support for setting log level by packages.
If you have a class: com.example.app.MyClass

None of these the configuration takes effect:
com.example.app=DEBUG
com.example._=DEBUG
com.example.app._=DEBUG

There is no way to set log level like this. only directly by giving the full tag name.

**Comment by philippkumar** [comment]
Resolved with pull request: https://github.com/akquinet/androlog/pull/5/files
