### ISSUE TITLE
Problems with androlog configuration from my-file.properties

### ISSUE THREAD

**Issue by zasadnyy** [techatspree/androlog#6]
Hello,
I've noticed small bug either in documentation or in logger initialization code. 
In docs we have sample:

``` java
Log.init("my-file"); // Use the my-file.properties file
```

but according to my tests this approach doesn't work, in order to fix it, we simply need to add file extension to init method parameter, e.g.:

``` java
Log.init("my-file.properties"); // Use the my-file.properties file
```

Another option is to modify initialization code in `de.akquinet.android.androlog.Log.init(Context context, String fileName)` method, now code looks like:

``` java
String file = fileName;
if (file == null && context != null) {
    file = context.getPackageName() + ".properties";
}
```

Updated and fixed version should look like:

``` java
String file = fileName;
if (file == null && context != null) {
     file = context.getPackageName();
}
file = file  + ".properties"
```

Best regards, 
Vitaliy.

**Comment by ebiermann** [comment]
Hello Vitaliy,

sorry for the late reply. I fixed the bug. You can now either provide the full file name my-file.properties or just my-file.

Best Regards,
Enrico

**Comment by zasadnyy** [comment]
Hello Enrico!

Thanks for notification.

Best Regards,
_Vitaliy Zasadnyy_

gplus: gplus.to/zasadnyy
http://zasadnyy.org.ua/

2013/2/1 Enrico Biermann notifications@github.com
