### ISSUE TITLE
version in poms is wrong

### ISSUE THREAD

**Issue by michaelayates** [techatspree/androlog#9]
Commit 4b728e3 merged a maven version 1.0.5-5bcac64.paloma.1 over the top of the master branch version 1.0.6-SNAPSHOT

Suggest master should be changed back to 1.0.6-SNAPSHOT

This will allow 1.0.6 to be released.

As there hasn't been a point release in quite a long time suggest a release of 1.0.6

**Comment by ebiermann** [comment]
Hello Michael,

I will fix the version number tomorrow. A new release is reasonable too and we will do it shortly.

Thanks,
Enrico

**Comment by ebiermann** [comment]
The version number is fixed and the release should be synced to Central soon.
